[package]
name = "tachfileto"
version = "0.1.0"
description = "High Performance Evidence Loading"
edition = "2021"

[dependencies]
tauri = { version = "1", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
